### ISSUE TITLE
no map change

### ISSUE THREAD

**Issue by asdfxD** [Cruze03/cs2_WorkshopDefaultMap#1]
does not work, added de_biome in WorkshopDefaultMap.txt

Loading plugin: WorkshopDefaultMap
Registering listener for OnMapStart with 1
Finished loading plugin: Workshop Collection Default Map
All managed modules were loaded. 1 plugins loaded.

after restarting the server it does not change the map, it's still de_dust2

**Comment by Cruze03** [comment]
Hey! I pushed v0.2 in the releases. Please check that out and let me know how it goes :) Sorry about that bug.

Edit: Also make sure hibernation is turned off. (`sv_hibernate_when_empty false`)

**Comment by Cruze03** [comment]
Closing since no response. Re-open if your issues persists!
