### ISSUE TITLE
enhancement: Update release package folder structure

### ISSUE THREAD

**Issue by profound-killah** [Cruze03/cs2_WorkshopDefaultMap#2]
Would like to request that you update the folder structure of the releases to make it easier to install for new users.

current structure: 
```
WorkshopDefaultMap/
└── WorkshopDefaultMap
    ├── WorkshopDefaultMap.deps.json
    ├── WorkshopDefaultMap.dll
    ├── WorkshopDefaultMap.pdb
    └── WorkshopDefaultMap.txt
```

suggested structure:
```
addons/
├── counterstrikesharp
   ├── plugins
     └── WorkshopDefaultMap
        ├── WorkshopDefaultMap.deps.json
        ├── WorkshopDefaultMap.dll
        ├── WorkshopDefaultMap.pdb
       └── WorkshopDefaultMap.txt
```

**Comment by Soulplayer** [comment]
I cannot get this plugin to work even if I follow your directions...

**Comment by Cruze03** [comment]
Thank you for your recommendation! Did this in the [latest release](https://github.com/Cruze03/cs2_WorkshopDefaultMap/releases/latest)

@Soulplayer Try the latest and let me know if it still doesn't work
